USE [master]
GO
/****** Object:  Database [TpArqWeb]    Script Date: 2026-06-06 10:40:51 ******/
CREATE DATABASE [TpArqWeb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TpArqWeb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\TpArqWeb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TpArqWeb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\TpArqWeb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [TpArqWeb] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TpArqWeb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TpArqWeb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TpArqWeb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TpArqWeb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TpArqWeb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TpArqWeb] SET ARITHABORT OFF 
GO
ALTER DATABASE [TpArqWeb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TpArqWeb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TpArqWeb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TpArqWeb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TpArqWeb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TpArqWeb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TpArqWeb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TpArqWeb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TpArqWeb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TpArqWeb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TpArqWeb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TpArqWeb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TpArqWeb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TpArqWeb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TpArqWeb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TpArqWeb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TpArqWeb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TpArqWeb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TpArqWeb] SET  MULTI_USER 
GO
ALTER DATABASE [TpArqWeb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TpArqWeb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TpArqWeb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TpArqWeb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TpArqWeb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TpArqWeb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [TpArqWeb] SET QUERY_STORE = ON
GO
ALTER DATABASE [TpArqWeb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
ALTER AUTHORIZATION ON DATABASE::[TpArqWeb] TO [PC-Escritorio-L\Lauta]
GO
USE [TpArqWeb]
GO
/****** Object:  Table [dbo].[BITACORAEVENTOS]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BITACORAEVENTOS](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[idusuario] [int] NULL,
	[fecha] [datetime] NULL,
	[accion] [varchar](50) NULL,
 CONSTRAINT [PK_BITACORAEVENTOS] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[BITACORAEVENTOS] TO  SCHEMA OWNER 
GO
/****** Object:  Table [dbo].[ETIQUETA]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ETIQUETA](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](50) NOT NULL,
 CONSTRAINT [PK_ETIQUETA] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[ETIQUETA] TO  SCHEMA OWNER 
GO
/****** Object:  Table [dbo].[IDIOMA]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IDIOMA](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](50) NOT NULL,
	[pordefecto] [bit] NOT NULL,
	[listoparausar] [bit] NOT NULL,
 CONSTRAINT [PK_Idioma] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[IDIOMA] TO  SCHEMA OWNER 
GO
/****** Object:  Table [dbo].[INSUMO]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INSUMO](
	[id] [int] NOT NULL,
	[material] [int] NOT NULL,
	[diametromilimetros] [decimal](5, 2) NOT NULL,
	[color] [nvarchar](50) NOT NULL,
	[marca] [nvarchar](100) NOT NULL,
	[kilogramos] [decimal](12, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[INSUMO] TO  SCHEMA OWNER 
GO
/****** Object:  Table [dbo].[PERMISOS]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERMISOS](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](50) NOT NULL,
	[tipo] [varchar](50) NULL,
 CONSTRAINT [PK_PERMISOS] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[PERMISOS] TO  SCHEMA OWNER 
GO
/****** Object:  Table [dbo].[PERMISOS_PERMISOS]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERMISOS_PERMISOS](
	[idpermisopadre] [int] NOT NULL,
	[idpermisohijo] [int] NOT NULL,
 CONSTRAINT [PK_PERMISOS_PERMISOS] PRIMARY KEY CLUSTERED 
(
	[idpermisopadre] ASC,
	[idpermisohijo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[PERMISOS_PERMISOS] TO  SCHEMA OWNER 
GO
/****** Object:  Table [dbo].[PIEZAIMPRESA]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PIEZAIMPRESA](
	[id] [int] NOT NULL,
	[tiempoimpresionminutos] [int] NOT NULL,
	[costodiseno] [decimal](18, 2) NOT NULL,
	[pesoconsumidogramos] [decimal](12, 2) NOT NULL,
	[insumoid] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[PIEZAIMPRESA] TO  SCHEMA OWNER 
GO
/****** Object:  Table [dbo].[PRODUCTO]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTO](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [nvarchar](200) NOT NULL,
	[preciobase] [decimal](18, 2) NOT NULL,
	[imagen] [varbinary](max) NULL,
	[stock] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[PRODUCTO] TO  SCHEMA OWNER 
GO
/****** Object:  Table [dbo].[TABLA_DVV]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TABLA_DVV](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombretabla] [varchar](50) NULL,
	[digitovertical] [varchar](70) NULL,
 CONSTRAINT [PK_TABLA_DVV] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[TABLA_DVV] TO  SCHEMA OWNER 
GO
/****** Object:  Table [dbo].[TRADUCCION]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRADUCCION](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[ididioma] [int] NOT NULL,
	[idetiqueta] [int] NOT NULL,
	[texto] [varchar](50) NOT NULL,
 CONSTRAINT [PK_TRADUCCION] PRIMARY KEY CLUSTERED 
(
	[id] ASC,
	[ididioma] ASC,
	[idetiqueta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[TRADUCCION] TO  SCHEMA OWNER 
GO
/****** Object:  Table [dbo].[USUARIOS]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIOS](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombredeusuario] [varchar](50) NOT NULL,
	[nombre] [varchar](50) NOT NULL,
	[apellido] [varchar](50) NOT NULL,
	[contrasenia] [varchar](50) NOT NULL,
	[correo] [varchar](50) NOT NULL,
	[ididioma] [int] NULL,
 CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[USUARIOS] TO  SCHEMA OWNER 
GO
/****** Object:  Table [dbo].[USUARIOS_PERMISOS]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIOS_PERMISOS](
	[idusuario] [int] NOT NULL,
	[idpermiso] [int] NOT NULL,
 CONSTRAINT [PK_USUARIOS_PERMISOS] PRIMARY KEY CLUSTERED 
(
	[idusuario] ASC,
	[idpermiso] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[USUARIOS_PERMISOS] TO  SCHEMA OWNER 
GO
ALTER TABLE [dbo].[INSUMO]  WITH CHECK ADD  CONSTRAINT [FK_INSUMO_PRODUCTO] FOREIGN KEY([id])
REFERENCES [dbo].[PRODUCTO] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[INSUMO] CHECK CONSTRAINT [FK_INSUMO_PRODUCTO]
GO
ALTER TABLE [dbo].[PIEZAIMPRESA]  WITH CHECK ADD  CONSTRAINT [FK_PIEZAIMPRESA_INSUMO] FOREIGN KEY([insumoid])
REFERENCES [dbo].[INSUMO] ([id])
GO
ALTER TABLE [dbo].[PIEZAIMPRESA] CHECK CONSTRAINT [FK_PIEZAIMPRESA_INSUMO]
GO
ALTER TABLE [dbo].[PIEZAIMPRESA]  WITH CHECK ADD  CONSTRAINT [FK_PIEZAIMPRESA_PRODUCTO] FOREIGN KEY([id])
REFERENCES [dbo].[PRODUCTO] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PIEZAIMPRESA] CHECK CONSTRAINT [FK_PIEZAIMPRESA_PRODUCTO]
GO
/****** Object:  StoredProcedure [dbo].[ACCION_LISTAR]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[ACCION_LISTAR]
AS
BEGIN
	SELECT * FROM PERMISOS WHERE tipo IS NOT NULL
END
GO
ALTER AUTHORIZATION ON [dbo].[ACCION_LISTAR] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[BITACORAEVENTOS_INSERTAR]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[BITACORAEVENTOS_INSERTAR]
@idusuario int, @fecha datetime, @accion varchar(50)
AS
BEGIN
	INSERT INTO BITACORAEVENTOS VALUES (@idusuario, @fecha, @accion)
END
GO
ALTER AUTHORIZATION ON [dbo].[BITACORAEVENTOS_INSERTAR] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[BITACORAEVENTOS_LISTAR]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[BITACORAEVENTOS_LISTAR]
AS
BEGIN
	SELECT * FROM BITACORAEVENTOS
END
GO
ALTER AUTHORIZATION ON [dbo].[BITACORAEVENTOS_LISTAR] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[IDIOMA_BORRAR]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[IDIOMA_BORRAR]
@id int
AS
BEGIN
	DELETE FROM TRADUCCION WHERE ididioma = @id
	DELETE FROM IDIOMA WHERE id = @id
END
GO
ALTER AUTHORIZATION ON [dbo].[IDIOMA_BORRAR] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[IDIOMA_BUSCAR]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[IDIOMA_BUSCAR]
@nombre varchar(50)
AS
BEGIN
	SELECT * FROM IDIOMA WHERE nombre = @nombre
END
GO
ALTER AUTHORIZATION ON [dbo].[IDIOMA_BUSCAR] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[IDIOMA_EDITAR]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[IDIOMA_EDITAR]
@id int, @nombre varchar(50), @listoparausar bit
AS
BEGIN
	UPDATE IDIOMA SET 
		nombre = @nombre,
		listoparausar = @listoparausar
	WHERE id = @id
END
GO
ALTER AUTHORIZATION ON [dbo].[IDIOMA_EDITAR] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[IDIOMA_INSERTAR]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[IDIOMA_INSERTAR]
@nombre varchar(50), @pordefecto bit, @listoparausar bit
AS
BEGIN
	INSERT INTO IDIOMA VALUES (@nombre, @pordefecto, @listoparausar)
	--Cree un trigger para cuando se inserte un nuevo idioma se puedan crear las traducciones de forma automática
END
GO
ALTER AUTHORIZATION ON [dbo].[IDIOMA_INSERTAR] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[IDIOMA_LISTAR]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[IDIOMA_LISTAR]
AS
BEGIN
	SELECT * FROM IDIOMA
END
GO
ALTER AUTHORIZATION ON [dbo].[IDIOMA_LISTAR] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[OBTENER_TRADUCCIONES]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[OBTENER_TRADUCCIONES]
@ididioma int
AS
BEGIN
	SELECT t.id AS 'idtraduccion', i.id AS 'ididioma', i.nombre AS 'nombreidioma', i.pordefecto, e.id AS 'idetiqueta', e.nombre AS 'nombreetiqueta', t.texto AS 'traduccion' FROM TRADUCCION t INNER JOIN IDIOMA i ON t.ididioma = i.id INNER JOIN ETIQUETA e ON t.idetiqueta = e.id WHERE i.id = @ididioma
END
GO
ALTER AUTHORIZATION ON [dbo].[OBTENER_TRADUCCIONES] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[PERMISO_INSERTAR]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[PERMISO_INSERTAR]
@nombre varchar(50), @tipo varchar(50)
AS
BEGIN
	INSERT INTO PERMISOS VALUES (@nombre, @tipo)
	--SELECT id AS LastID FROM PERMISOS WHERE id = @@Identity
END
GO
ALTER AUTHORIZATION ON [dbo].[PERMISO_INSERTAR] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[PERMISO_LISTAR_RECURSIVO]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[PERMISO_LISTAR_RECURSIVO]
@where varchar(50)
AS
BEGIN
	WITH recursivo AS	(
							SELECT PP2.idpermisopadre, PP2.idpermisohijo FROM PERMISOS_PERMISOS PP2
							WHERE PP2.idpermisopadre = @where --acá se va variando la familia que busco
							UNION ALL 
							SELECT PP1.idpermisopadre, PP1.idpermisohijo FROM PERMISOS_PERMISOS PP1 
							inner join recursivo rec ON rec.idpermisohijo = PP1.idpermisopadre
						)
						SELECT rec.idpermisopadre, rec.idpermisohijo, P.id, P.nombre, P.tipo
						FROM recursivo rec 
						inner join PERMISOS P ON rec.idpermisohijo = P.id
END
GO
ALTER AUTHORIZATION ON [dbo].[PERMISO_LISTAR_RECURSIVO] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[PERMISO_PERMISO_BORRAR]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[PERMISO_PERMISO_BORRAR]
@id int
AS
BEGIN
	DELETE FROM PERMISOS_PERMISOS WHERE idpermisopadre = @id
END
GO
ALTER AUTHORIZATION ON [dbo].[PERMISO_PERMISO_BORRAR] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[PERMISO_PERMISO_INSERTAR]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[PERMISO_PERMISO_INSERTAR]
@idpermisopadre int, @idpermisohijo int
AS
BEGIN
	INSERT INTO PERMISOS_PERMISOS VALUES (@idpermisopadre, @idpermisohijo) 
END
GO
ALTER AUTHORIZATION ON [dbo].[PERMISO_PERMISO_INSERTAR] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[PRODUCTO_EDITAR_STOCK]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[PRODUCTO_EDITAR_STOCK]
@id int, @cantidad int
AS
BEGIN
	UPDATE PRODUCTO SET 
        stock = stock - @cantidad
    WHERE id = @id
END

GO
ALTER AUTHORIZATION ON [dbo].[PRODUCTO_EDITAR_STOCK] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[PRODUCTO_LISTAR]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[PRODUCTO_LISTAR]
AS
BEGIN
	SELECT p.id, p.nombre, p.preciobase, p.imagen, p.stock,
    
    -- Columna virtual para que tu backend sepa qué clase instanciar
    CASE 
        WHEN i.id IS NOT NULL THEN 'Insumo'
        WHEN pi.id IS NOT NULL THEN 'PiezaImpresa'
    END AS tipoproducto,

    -- Campos exclusivos de Insumos (Vendrán en NULL si el producto es una pieza)
    i.material,
    i.diametromilimetros,
    i.color,
    i.marca,
    i.kilogramos,

    -- Campos exclusivos de Piezas Impresas (Vendrán en NULL si el producto es un insumo)
    pi.tiempoimpresionminutos,
    pi.costodiseno,
    pi.insumoid

    FROM PRODUCTO p
    LEFT JOIN INSUMO i ON p.id = i.id
    LEFT JOIN PIEZAIMPRESA pi ON p.id = pi.id;
END
GO
ALTER AUTHORIZATION ON [dbo].[PRODUCTO_LISTAR] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[REALIZAR_BACKUP]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[REALIZAR_BACKUP]
@nombrebd varchar(50), @rutabackup varchar(200)
AS
BEGIN
	BACKUP DATABASE @nombrebd TO DISK = @rutabackup
END
GO
ALTER AUTHORIZATION ON [dbo].[REALIZAR_BACKUP] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[ROL_LISTAR]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[ROL_LISTAR]
AS
BEGIN
	SELECT * FROM PERMISOS WHERE tipo IS NULL
END
GO
ALTER AUTHORIZATION ON [dbo].[ROL_LISTAR] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[TABLA_DVV_INSERTAR]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[TABLA_DVV_INSERTAR] --Digito verificador vertical
@nombretabla varchar(50), @digitovertical varchar(70)
AS
BEGIN
	IF EXISTS (SELECT * FROM TABLA_DVV WHERE nombretabla = @nombretabla)
	BEGIN
		UPDATE TABLA_DVV SET 
			digitovertical = @digitovertical
		WHERE nombretabla = @nombretabla;
	END
	ELSE
	BEGIN
		INSERT INTO TABLA_DVV VALUES (@nombretabla, @digitovertical);
	END
END
GO
ALTER AUTHORIZATION ON [dbo].[TABLA_DVV_INSERTAR] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_BORRAR]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[USUARIO_BORRAR]
@id int
AS 
BEGIN
	DELETE FROM USUARIOS WHERE id = @id
END
GO
ALTER AUTHORIZATION ON [dbo].[USUARIO_BORRAR] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_BUSCAR]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[USUARIO_BUSCAR]
@nombredeusuario varchar(50), @contrasenia varchar(50)
AS
BEGIN
	SELECT * FROM USUARIOS WHERE nombredeusuario = @nombredeusuario AND contrasenia = @contrasenia
END
GO
ALTER AUTHORIZATION ON [dbo].[USUARIO_BUSCAR] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_BUSCARID]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USUARIO_BUSCARID]
@id int
AS
BEGIN
	SELECT * FROM USUARIOS WHERE id = @id
END
GO
ALTER AUTHORIZATION ON [dbo].[USUARIO_BUSCARID] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_EDITAR]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[USUARIO_EDITAR]
@id int, @nombredeusuario varchar(50), @contrasenia varchar(50), @nombre varchar(50), @apellido varchar(50), @correo varchar(50), @ididioma int 
AS 
BEGIN
	update USUARIOS SET 
		nombredeusuario = @nombredeusuario, 
		contrasenia = @contrasenia,
		nombre = @nombre,
		apellido = @apellido,
		correo = @correo,
		ididioma = @ididioma
	WHERE id = @id
END
GO
ALTER AUTHORIZATION ON [dbo].[USUARIO_EDITAR] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_INSERTAR]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USUARIO_INSERTAR]
@nombredeusuario varchar(50), @nombre varchar(50), @apellido varchar(50), @contrasenia varchar(50), @correo varchar(50), @ididioma int
AS 
BEGIN
	INSERT INTO USUARIOS VALUES (@nombredeusuario, @nombre, @apellido, @contrasenia, @correo, @ididioma)
END
GO
ALTER AUTHORIZATION ON [dbo].[USUARIO_INSERTAR] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_LISTAR]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[USUARIO_LISTAR]
AS
BEGIN
	SELECT * FROM USUARIOS
END
GO
ALTER AUTHORIZATION ON [dbo].[USUARIO_LISTAR] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[USUARIO_PERMISO_LISTAR]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[USUARIO_PERMISO_LISTAR]
@id int
AS
BEGIN
	SELECT P.* FROM USUARIOS_PERMISOS UP INNER JOIN PERMISOS P ON UP.idpermiso = P.id WHERE idusuario = @id
END
GO
ALTER AUTHORIZATION ON [dbo].[USUARIO_PERMISO_LISTAR] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[USUARIOS_PERMISOS_BORRAR]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USUARIOS_PERMISOS_BORRAR]
@id int
AS
BEGIN
	DELETE FROM USUARIOS_PERMISOS WHERE idusuario = @id
END
GO
ALTER AUTHORIZATION ON [dbo].[USUARIOS_PERMISOS_BORRAR] TO  SCHEMA OWNER 
GO
/****** Object:  StoredProcedure [dbo].[USUARIOS_PERMISOS_INSERTAR]    Script Date: 2026-06-06 10:40:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[USUARIOS_PERMISOS_INSERTAR]
@idusuario int, @idpermiso int
AS
BEGIN
	INSERT INTO USUARIOS_PERMISOS VALUES (@idusuario, @idpermiso)
END
GO
ALTER AUTHORIZATION ON [dbo].[USUARIOS_PERMISOS_INSERTAR] TO  SCHEMA OWNER 
GO
USE [master]
GO
ALTER DATABASE [TpArqWeb] SET  READ_WRITE 
GO
